name: Demo

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  demo:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Run demo
        run: mvn -B -ntp -pl demo -am verify
